apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: open-cluster-management-observability
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: mco-bucket
      endpoint: minio.minio.svc.cluster.local:9000
      insecure: true
      access_key: minio
      secret_key: minio123
