apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: observability
  annotations:
    openshift.io/display-name: "Observability Project"
    openshift.io/description: "Namespace pour toutes les applications et policies liées à l'observabilité"
---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: openshift-gitops
spec:
  description: "Projet Argo CD pour toutes les policies ACM et dashboards observabilité"
  sourceRepos:
    - 'https://github.com/atiouajni/open-code-quest-observability.git'
  destinations:
    - namespace: observability
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: openshift-gitops
spec:
  project: observability
  source:
    repoURL: 'https://github.com/atiouajni/open-code-quest-observability.git'
    targetRevision: main
    path: manifests/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
