apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-workload-monitoring-policy
  namespace: openshift-gitops
spec:
  project: observability
  source:
    repoURL: 'https://github.com/atiouajni/open-code-quest-observability.git'
    targetRevision: main
    path: manifests/policies/user-workload-monitoring-policy
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
