apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: observability
  annotations:
    openshift.io/display-name: "Observability Project"
    openshift.io/description: "Namespace pour toutes les applications et policies liées à l'observabilité"
---

apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd-observability
  namespace: observability
spec:
  server:
    route:
      enabled: true
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: '[groups]'
  repo:
    env:
      - name: KUSTOMIZE_PLUGIN_HOME
        value: /etc/kustomize/plugin
    initContainers:
      - args:
          - '-c'
          - cp /policy-generator/PolicyGenerator-not-fips-compliant /policy-generator-tmp/PolicyGenerator
        command:
          - /bin/bash
        image: 'registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:2.14.0-1282511'
        name: policy-generator-install
        resources: {}
        volumeMounts:
          - mountPath: /policy-generator-tmp
            name: policy-generator
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
      - mountPath: /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
        name: policy-generator
    volumes:
      - emptyDir: {}
        name: policy-generator
  kustomizeBuildOptions: '--enable-alpha-plugins'
