apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: mco-pull-secret
spec:
  remediationAction: enforce
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: multiclusterhub-operator-pull-secret
          namespace: open-cluster-management-observability
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: '{{hub fromSecret "openshift-config" "pull-secret" ".dockerconfigjson" hub}}'

