apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-observability-operator
  namespace: open-cluster-management-observability
spec:
  installPlanApproval: Automatic
  name: multicluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
