apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: require-mco-with-minio-persistent
  namespace: policies
placementBindingDefaults:
  name: mco-minio-binding
policyDefaults:
  remediationAction: enforce
  severity: high
placement:
    labelSelector:
      matchLabels:
        local-cluster: "true"
policies:
  - name: mco-operator
    manifests:
      - path: mco-operatorgroup.yaml
      - path: mco-subscription.yaml
  - name: minio
    manifests:
      - path: minio-namespace.yaml
      - path: minio-pvc.yaml
      - path: minio-statefulset.yaml
      - path: minio-service.yaml
      - path: minio-secret.yaml
  - name: mco-instance
    manifests:
      - path: multiclusterobservability.yaml
