apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: grafana-obs
    folders: grafana-obs
  name: grafana-obs
  namespace: observability
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: root
      admin_user: root
  route:
    spec:
      to:
        kind: Service
        name: grafana-obs-service
        weight: 100

