apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: require-grafana-operator
  namespace: policies
placementBindingDefaults:
  name: grafana-operator-binding
policyDefaults:
  remediationAction: enforce
  severity: high
placementDefaults:
  name: local-cluster-placement
  clusterSelectors:
    matchLabels:
      local-cluster: 'true'
policies:
  - name: grafana-operator
    manifests:
      - path: grafana-namespace.yaml
      - path: grafana-operatorgroup.yaml
      - path: grafana-subscription.yaml
